version: "3.8"
services:
  runner:
    container_name: github-action-runner
    build:
      context: ./
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/home/docker/.docker/run/docker.sock:ro
    network_mode: host
