version: "3.8"
services:
  runner:
    build:
      context: ./
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == worker
    env_file:
      - .env
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
