services:
  runner:
    build:
      context: ./
      args:
        - DOCKER_GROUP
    deploy:
      mode: replicated
      replicas: 4
      placement:
        constraints:
          - node.role == worker
    env_file:
      - .env
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
